<?php

/*function asset_login_init(){
	ctools_include('modal');
    ctools_modal_add_js();	
}*/

function asset_login_permission() {
  return array(
    'asset_login_per' => array(
      'title' => t('OTP Login Permission'),
    )
	
  );
}

function asset_login_menu() {
	$items=array();
	
	/*$items['otpmymodal/%ctools_js'] = array(
    	'page callback' => 'mymodal_login_callback',
    	'page arguments' => array(1),
		'access arguments' => TRUE,
    	'access callback' => TRUE,
    	'type' => MENU_CALLBACK,
    );*/
	
	$items['assetlogin'] = array(
		'title'=>'ASSET Login',
		'page callback'=>'drupal_get_form',
		'page arguments'=>array('asset_login_form'),
		'access arguments' => array('asset_login_per'),
		'access callback'=>TRUE,
		'type' 				=> 	MENU_CALLBACK,
	  );
	
	return $items;
	
}



function asset_login_form($form, &$form_state) {
	
	global $base_root, $base_path;
  drupal_add_css(drupal_get_path('module', 'applicant_registration') . '/css/sky-forms.css');
  drupal_add_css(drupal_get_path('module', 'applicant_registration') . '/css/form-design.css');
  
  	if(isset($_SESSION['OTP'])){
		unset($_SESSION['OTP']);
	}
	
	$form['#attributes']['class'][] = 'sky-form custom-form-main';
	$form['#theme'] = 'asset_login_page';
	
	
	
	$form['mobile'] = array(
	   '#title'=>'',
	   '#maxlength' => 10, 
	   '#type' => 'textfield',
	   '#attributes' => array('class'=>array(''), 'placeholder'=>'Enter your HRMS ID', 'autocomplete' => 'off',),
	   '#prefix'=>'<div class="col-md-12"><label>Enter your HRMS ID</label>',
	   '#suffix' => '</div>',
	);	
	
	$form['showmsg_success'] = array(
		'#prefix' => '<div id="success_div">',
		'#suffix' => '</div>',   
     );
	 
	$form['showmsg_error'] = array(
		'#prefix' => '<div id="error_div">',
		'#suffix' => '</div>',   
     ); 
	 
	  $form['endtimer'] = array(
			'#prefix' => '<div id="divEndTimer">',
			'#suffix' => '</div>',   
		 ); 
	 
	  $form['showtimer'] = array(
			'#prefix' => '<div id="divCounter">',
			'#suffix' => '</div>',   
		 ); 
	
	$form['otp'] = array(
	   '#title'=>'',
	   '#maxlength' => 6, 
	   '#type' => 'textfield',
	   '#attributes' => array('class'=>array(''), 'placeholder'=>'Enter 6 Digit OTP', 'autocomplete' => 'off'),
	   '#prefix' => '<div class="col-md-12"><label>Enter One Time Password(OTP)</label>',
	   '#suffix' => '</div>',
	);
	
	
 $form['sent_otp'] = array (
        '#type' => 'submit',
        '#value' => 'Generate OTP',
		'#id'=>'genotp',
		'#attributes' => array('class'=>array('send-otp')),
		'#ajax' => array(
			'callback' => '_handle_form_submit_asset',
			'effect' => 'fade',
		),
		'#prefix' => '',
  		'#suffix' => '',
     ); 
	 
 $form['submit_send'] = array (
        '#type' => 'submit',
        '#value' => 'login',
		'#attributes' => array('class'=>array('login')),
		/*'#ajax' => array(
			'callback' => '_handle_otp_final_submit',
			'effect' => 'fade',
		),*/
		'#prefix' => '',
  		'#suffix' => '',
     ); 	 
	
    return $form;
}

function asset_login_theme($existing, $type, $theme, $path){
  
  
  $items = array();	
  $items['asset_login_page'] = array(
	  'render element' => 'form',
	  //'path' => drupal_get_path('module', 'custom_donate') . '/templates',
	  'template' => 'asset_login_part',
	  /*'preprocess functions' => array(
	  'demo2_preprocess_demo2_form'
	  ),*/
  );
  
  return $items;
  
}

function asset_login_form_validate($form, &$form_state) {
  if (!$form_state['values']['mobile']) {
    form_set_error('mobile', 'You must enter mobile number before continuing');    
  }
}

function asset_login_form_submit($form, &$form_state) {
	$form_state['rebuild'] = true;
	$form_state['flag'] = 1;
	
	if($form_state['values']['op']=='login'){
	
		if ($_SESSION['timeout'] + 5 * 60 < time()) {
		 unset($_SESSION['OTP']);
		} else {
		 	
			$query = db_select('a_user_details', 'us');
			$query->leftJoin('users', 'u', 'u.uid=us.uid');
			$query ->fields('us', array( 'fname','dob','mobile','email','status'));
			$query ->fields('u', array( 'uid','name','pass'));
			$query->condition('us.hrms_id',trim($form_state['values']['mobile']),'=');
			$result = $query->execute();
			$data = $result->fetchObject();
			
			
			$uid = $data->uid;
			$username = $data->name;
		 	if($uid)
			{
			  if(isset($_SESSION['OTP']) && $_SESSION['OTP']== trim($form_state['values']['otp'])){	
				  $user_obj = user_load_by_name($username);
				  $access_granted = in_array('asset', $user_obj->roles);
				  if ($access_granted){
					  $form_state = array();
					  $form_state['uid'] = $user_obj->uid;      
					  user_login_submit(array(), $form_state);
					  unset($_SESSION['OTP']);
					  drupal_goto('dashboard');
					  return true;
				  }else{
					 unset($_SESSION['OTP']); 
					 form_set_error('', t('Only asset user can login!!'));
					 return FALSE; 
				  }
			  }else{
				  	unset($_SESSION['OTP']);
					drupal_set_message('Invalid OTP! Please re-generate OTP and Enter Correct OTP', $type='warning');
					drupal_goto('assetlogin');
				   	//form_set_error('', t('Invalid OTP! Please Enter OTP'));
					//return FALSE; 
			   }
			}
			else
			{
				unset($_SESSION['OTP']);
				drupal_set_message('You are not authenticated user', $type='warning');
				drupal_goto('assetlogin');
				//form_set_error('', t('You are not authenticated user'));
				//return false;
			}
		 
		}
		exit;
	}
}



function _handle_form_submit_asset($form, &$form_state) {
	
	global $base_root, $base_path, $user;
	
	$hrms_id = trim($form_state['values']['mobile']);
	
	$query = db_select('users', 'u');
	$query->leftJoin('a_user_details', 'ud', 'u.uid = ud.uid');
	$query->fields('u', array('uid','name','access','created','status'));
	$query->fields('ud', array('fname','hrms_id','mobile'));
	$query->condition('u.name', $hrms_id, '=');
	$result = $query->execute();
	$userData = $result->fetchAssoc();
	//print_r($userData);
	//echo "--->".$userData['mobile'];
	//exit;
	$rand_num = rand(100000,999999); 
	$otp_msg = 'Use '.$rand_num.' as your login OTP (One Time Password), it is valid for 5 minute. OTP is confidential, we never call to verify your OTP. Labour Department, WB';
	
	//$userData['mobile'] = '7003853722';
	
	$res = send_otp_for_asset($userData['mobile'],$otp_msg,'1107161492332110331'); 
	$_SESSION['OTP'] = $rand_num;
	$_SESSION['timeout'] = time();
	
	$commands = array();
	
	$number =  $userData['mobile'];
	$masked =  str_pad(substr($number, -4), strlen($number), '*', STR_PAD_LEFT);
	//print $masked;
    //exit;
	
	$form=array();
	if($res == 'success'){
		//$output='OTP has been sent to you on your mobile number: '.$form_state['values']['mobile'];
		
		$output='OTP has been sent on your mobile number: '.$masked;
		
		$form['showmsg_success'] = array(
		  '#prefix' => '<div id="success_div">'.$output,
		  '#suffix' => '</div>',   
		);
		
		$form['showmsg_error'] = array(
			'#prefix' => '<div id="error_div">',
			'#suffix' => '</div>',   
		 );
		 
		  $form['endtimer'] = array(
			'#prefix' => '<div id="divEndTimer">',
			'#suffix' => '</div>',   
		 );  
		 
		 $form['showtimer'] = array(
			'#prefix' => '<div id="divCounter"><script>getTimer()</script>',
			'#suffix' => '</div>',   
		 ); 
		 
		$commands[] =ajax_command_replace('#divEndTimer',drupal_render($form['endtimer']));
			 
		$commands[] =ajax_command_replace('#error_div',drupal_render($form['showmsg_error']));
			 
		$commands[] =ajax_command_replace('#success_div',drupal_render($form['showmsg_success']));
		
		$commands[] =ajax_command_replace('#divCounter',drupal_render($form['showtimer']));
		
	}else if($res == 'failure'){
		$output='Please enter correct hrms id!';	
		//$output='OTP service is under maintenance,please come back after some time!';	
		$form['showmsg_error'] = array(
			'#prefix' => '<div id="error_div">'.$output,
			'#suffix' => '</div>',   
		 );
		 
		 $form['showmsg_success'] = array(
		  '#prefix' => '<div id="success_div">',
		  '#suffix' => '</div>',   
		); 
			 
		$commands[] =ajax_command_replace('#error_div',drupal_render($form['showmsg_error']));
		$commands[] =ajax_command_replace('#success_div',drupal_render($form['showmsg_success']));
	}	  
		
		return array('#type' => 'ajax','#commands' => $commands);
	
	
}


function get_string_between_asset($string, $start, $end){
    $string = ' ' . $string;
    $ini = strpos($string, $start);
    if ($ini == 0) return '';
    $ini += strlen($start);
    $len = strpos($string, $end, $ini) - $ini;
    return substr($string, $ini, $len);
}

function send_otp_for_asset($dest='', $msg='', $template_id=''){
/*$uid    =    'wblbr.sms';
$pass    =    'K!dUS4I%252h';*/
$uid   = 'wblbr.otp';
$pass  ='K!ydd64%252h';
$send    =    'WBLABR';
$url    =    "https://smsgw.sms.gov.in/failsafe/HttpLink?";
$data     =  "username=$uid&pin=$pass&message=$msg&mnumber=$dest&signature=$send&dlt_entity_id=1101757270000028157&dlt_template_id=$template_id";
//echo "https://smsgw.sms.gov.in/failsafe/HttpLink?username=$uid&pin=$pass&message=$msg&mnumber=$dest&signature=$send";
$ch     =     curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER,false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST,1);
curl_setopt($ch, CURLOPT_CAINFO,'/etc/pki/tls/certs/ca-bundle.crt');
$test=curl_exec($ch);
$arr = explode("=",get_string_between_asset($test,'~','&'));
if(trim($arr[1]) == 'API000')
{
	return 'success';
}else{
	return 'failure';
}

}


