<?php
/**
 * @file
 * Module file for Housing Schemes Services.
 * Contains the resource declarations for the service APIs
 * and other commons functions/hooks. if necessary
 */

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data.
 */
function ssdg_webservice_services_resources() {
  $resources = array();

//Include the necessary inc files.
  module_load_include('inc', 'ssdg_webservice', 'includes/ssdg_webservice.services');

//Service Apis for contents.
  $resources += ssdg_webservice_services_resource();
  //print_r($resources); exit;
  return $resources;
}