<?php

 //module_load_include('inc', 'question_dashboard', 'includes/question_dashboard.validate');
 module_load_include('inc', 'question_dashboard', 'includes/question_dashboard.submit');
 
 
 
function question_dashboard_permission() {
  return array(
    'question_dashboard-per' => array(
      'title' => t('Permission'),
    ),	
  );
}


function question_dashboard_menu() {
  $items = array();
 
//for add of question

 $items['question-dashboard/add'] = array(
	'title' => 'Add Question',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('question_dashboard'),
	'access arguments' => array('question_dashboard-per'),
	//'access arguments' => array('access content'),
	'file' => 'question_dashboard.form.inc',
  );
  
  // for dashboard of question
  
  $items['question-dashboard'] = array(
	'title' => 'Dashboard of Question Wizard',
	//'page callback' => 'drupal_get_form',
	'page callback' => 'question_dashboard_form',
	'access arguments' => array('question_dashboard-per'),
	//'access arguments' => array('access content'),
	'file' => 'question_dashboard.form.inc',
  );
  
   // for edit of question
   
  $items['question-dashboard/edit/%'] = array(
	'title' => 'Question Edit',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('question_dashboard_edit_form',2),
	'access arguments' => array('question_dashboard-per'),
	//'access arguments' => array('access content'),
	'file' => 'question_dashboard.form.inc',
  );
    
  // for Status Change
  $items['question-dashboard/changeStatus/%/%'] = array(
	'title' => 'Question Status Change',
	'page callback' => 'question_dashboard_status_change',
	'page arguments' => array(2,3),
	'access arguments' => array('question_dashboard-per'),
	//'access arguments' => array('access content'),
	'file' => 'question_dashboard.form.inc',
  );
  
  return $items;
}

